# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

resources:
  repositories:
  - repository: Exam_Tool_Client
    type: git
    name: EFTA_Solutions/Exam_Tool_Client

trigger:
  branches:
    include:
    - master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- checkout: Exam_Tool_Client
- script: npm install
  displayName: 'Install Dependencies'
  workingDirectory: EFTA_Exam

- script: npm run build
  displayName: 'Build Electron App'
  workingDirectory: EFTA_Exam
  
- script: npm run package:test
  displayName: 'Package Electron App'
  workingDirectory: EFTA_Exam

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: |
       src/*
       public/*
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy project files'

- task: PublishPipelineArtifact@1
  inputs:
    artifactName: e2e-server
    targetPath: '$(Build.ArtifactStagingDirectory)'
    publishLocation: 'pipeline'
  displayName: 'Publish npm artifact'

