# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - master

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
  - repository: Exam_Tool_Client
    type: git
    name: EFTA_Solutions/Exam_Tool_Client


steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- checkout: self
- script: npm ci
  displayName: 'Install Dependencies'
  workingDirectory: EFTA_Exam\EFTA_Exam

- script: npm run build
  displayName: 'Build Electron App'
  
- script: npm run package
  displayName: 'Package Electron App'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'dist'  # Assuming your Electron Builder outputs to a 'dist' directory
    artifactName: 'electron-app'
    publishLocation: 'Container'
