# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

resources:
  repositories:
  - repository: Exam_Tool_Client
    type: git
    name: EFTA_Solutions/Exam_Tool_Client

trigger:
  branches:
    include:
    - master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- checkout: Exam_Tool_Client
- script: npm install
  displayName: 'Install Dependencies'
  workingDirectory: EFTA_Exam

- script: npm run build
  displayName: 'Build Electron App'
  workingDirectory: EFTA_Exam
  
- script: npm run package
  displayName: 'Package Electron App'
  workingDirectory: EFTA_Exam

# Create a new directory and copy the artifacts into it
- script: mkdir -p $(Build.ArtifactStagingDirectory)/EFTA_Exam
  displayName: 'Create Artifact Folder'
  

# Copy the release artifacts to the staging directory
- script: cp -r EFTA_Exam/release $(Build.ArtifactStagingDirectory)/EFTA_Exam
  displayName: 'Copy release artifacts to staging directory'

# Publish the release artifacts from the staging directory
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'EFTA_Exam' 
    artifactName: 'electron-app-release'
    publishLocation: 'Container'

